plugins:
  - rubocop-rspec
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-yard

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NoExpectationExample:
  AllowedPatterns:
    - assert_
    - is_expected_in_block

AllCops:
  Exclude:
    - "spec/dummy/node_modules/**/*"
    - "spec/dummy/public/**/*"
    - "spec/dummy/tmp/**/*"
    - "spec/dummy/log/**/*"
    - "spec/dummy/storage/**/*"
    - "spec/dummy/db/schema.rb"
    - "lib/generators/**/templates/**/*"

# YARD documentation configuration
YARD:
  Enabled: true

YARD/CollectionStyle:
  Enabled: true

YARD/CollectionType:
  Enabled: true

YARD/MeaninglessTag:
  Enabled: true

YARD/MismatchName:
  Enabled: true

YARD/TagTypePosition:
  Enabled: true

YARD/TagTypeSyntax:
  Enabled: true

Style/Documentation:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "db/migrate/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
